### PR TITLE
[FIX] Remove default `NB_API_QUERY_URL` value and fix ports used by full-stack setup script

### LINKED ISSUE #21: Non-robust default value for `NB_API_QUERY_URL` in Compose recipes
As (re-)discovered in https://github.com/neurobagel/planning/issues/111#issuecomment-1955461496, when the query tool is part of a deployment that is meant to be accessed from *other* machines, the URL used for the API that it talks to has to be provided as it would appear to an external user on their *own* machine.

The query tool essentially always behaves as if the user has downloaded it and then run it on their own machine. So, `NB_API_QUERY_URL` must be set to a URL that makes sense from outside the machine hosting the API, such as the public IP of the host, or the subdomain for the API if NGINX is set up on the machine.

One exception is if a user tries deploying our API stack on their local machine (and then tries the query tool from the same machine), in which case `NB_API_QUERY_URL` would need to be `localhost` (also because their laptop would not have a unique public IP). This should be documented clearly in a note to the user.

Meanwhile, we should update the default in the `.env` file to a clearly toy/must-be-changed URL, e.g.:
- 12.34.56.78
- XX.XX.XX.XX

- See also https://github.com/neurobagel/query-tool/pull/343

### LINKED ISSUE #39: `setup.sh` steps use host port for GraphDB home when called inside container
The following code needs to be modified for the full-stack Compose recipe, to use `NB_GRAPH_PORT` instead of `NB_GRAPH_PORT_HOST`:

https://github.com/neurobagel/recipes/blob/b5cf9d86529c43091e7df0c4810d41f3698a2adc/dev/setup.sh#L22-L28

https://github.com/neurobagel/recipes/blob/b5cf9d86529c43091e7df0c4810d41f3698a2adc/dev/graphdb_setup.sh#L131
(graphdb_setup.sh was originally meant to be called outside a container - maybe there's a way to avoid hardcoding which port it uses so it can be used either way?)

### PR DESCRIPTION
**Pull request by alyssadai**
- Closes #21 
- Closes #39 

Changes proposed in this pull request:

- Default value for `NB_API_QUERY_URL` removed, so this value now must always be manually provided
  - Replaced with placeholder in `template.env`
- `setup.sh` and `graphdb_setup.sh` now use the `NB_GRAPH_PORT` variable for GraphDB operations (more generic name also suits our plan to eventually have just one configurable port for GraphDB)

## Checklist
_This section is for the PR reviewer_

- [x] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see our [Contributing Guidelines](https://neurobagel.org/contributing/CONTRIBUTING#pull-request-guidelines) for more info)_
- [x] PR links to GitHub issue with mention `Closes #XXXX`
- [ ] Tests pass
- [ ] Checks pass

For new features:
- [ ] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions.

### CODE REVIEW

File: dev/graphdb_setup.sh [hunk 1]
```diff
@@ -128,12 +128,12 @@ echo "Environment variables have been set from ${ENV_FILE_PATH}."
...
 # Extract just the database name
 DB_NAME="${NB_GRAPH_DB#repositories/}"
-NB_GRAPH_PORT_HOST=${NB_GRAPH_PORT_HOST:-7200}
+NB_GRAPH_PORT=${NB_GRAPH_PORT:-7200}
 
 # Get the directory of this script to be able to find the data-config_template.ttl file
 SCRIPT_DIR=$(dirname "$0")
 
-echo "The GraphDB server is being accessed at http://localhost:${NB_GRAPH_PORT_HOST}."
+echo "The GraphDB server is being accessed at http://localhost:${NB_GRAPH_PORT}."
```
Comment (surchs) [inline dev/graphdb_setup.sh:136]:
```suggestion
echo "The GraphDB server is being accessed at inside the graphDB container http://localhost:${NB_GRAPH_PORT}."
```

My head is spinning a bit about what `localhost` can mean in all of these scenarios. Idea: since we really only expect this script to be run as part of the single `docker-compose.yml` recipe in the future - should we update these echos accordingly?

Comment (surchs) [reply dev/graphdb_setup.sh:136]: e.g. to understand that `localhost` is correct here you need to remember that
- this is running in a container, not host
- that it is running in the exact container that is running graphDB (otherwise you'd have to use `graph`, not `localhost`)
- and that by `localhost`, we're referring to the container itself, not the host machine

quite a bit of things to remember

File: dev/template.env [hunk 2]
```diff
@@ -37,8 +37,8 @@ NB_FAPI_PORT_HOST=8080
 NB_FAPI_TAG=latest
 
 # ---- CONFIGURATION FOR QUERY TOOL ----
-# URL of the f-API as it will appear to a user
-NB_API_QUERY_URL=http://localhost:8080
+# URL of the n-API/f-API the query to will talk to, as it appears to a user
+NB_API_QUERY_URL=http://XX.XX.XX.XX  # REPLACE WITH YOUR API URL (AND PORT, IF APPLICABLE) AS IT APPEARS ON A USER'S MACHINE, OR localhost:<port> IF QUERY TOOL WILL ONLY BE ACCESSED FROM ITS HOST MACHINE
```
Comment (surchs) [inline dev/template.env:41]: I'd say: let's default to having comments above the line. We already saw some cases where inline comments break - and they also look pretty bad if they are this long.

**Review by surchs — APPROVED** [review]
Thanks @alyssadai. 

Two comments, take a look.

After that :cook:
